{{- if not (.Values.general.install.externalSecret).regcred }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ with required "REGCRED missing!" .Values.REGCRED }}
    {{- $_ := required "REGCRED.auths missing or empty!" (or .auths nil) }}
    {{- range $k, $v :=  .auths }}
      {{- $_ := set $v "auth" (list $v.username ":" $v.password | join "" | b64enc)}}
    {{- end }}
    {{- .auths | mustToJson | b64enc }}
  {{- end }}
{{- end }}
