{{- if not (.Values.general.install.externalSecret).mqcerts }}
apiVersion: v1
kind: Secret
metadata:
  name: mqcerts
  namespace: {{ .Values.namespace }}
stringData:
{{ include "certs" (list . "{mq.key,mq.crt,isvgimRootCA.crt}") }}
{{- end }}
