{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: isvgimdata2
  namespace: {{ .Values.namespace }}
data:
{{- range $path, $_ := .Files.Glob "data-tpl/*.properties" }}
  {{ base $path }}: |
{{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{- end -}}
{{- range $path, $_ := .Files.Glob "data/*" }}
{{- if not (hasSuffix "encryptionKey.properties" $path) }}
  {{ base $path }}: {{ $.Files.Get $path | quote }}
{{- end }}
{{- end }}
