{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: isvgim-init
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "config/init/*.sh").AsConfig | indent 2 }}
binaryData:
{{ (.Files.Glob "config/init/*.jar").AsSecrets | indent 2 }}
