{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqcfg
  namespace: {{ .Values.namespace }}
data:
{{ tpl (.Files.Glob "config/mq/*").AsConfig . | indent 2 }}
