{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
{{- if not (.Values.general.install.externalSecret).metricscreds }}
apiVersion: v1
stringData:
  {{- $userName := ""                         }}
  {{- range $option := .Values.server.options }}
  {{-   if eq $option.name "libertyMetrics"   }}
  {{-     range $data := $option.data         }}
  {{-       if eq $data.name "userName"       }}
  {{-         $userName = $data.value         }}
  {{-       end                               }}
  {{-     end                                 }}
  {{-   end                                   }}
  {{- end                                     }}
  LIBERTYMETRICS_USERNAME: {{ $userName | quote }}
data:
  LIBERTYMETRICS_PASSWORD: {{  default "" .Values.LIBERTYMETRICS_PASSWORD | b64enc  }}
kind: Secret
metadata:
  name: metricscreds
  namespace: {{ .Values.namespace }}
{{- end }}
