apiVersion: v1
kind: Service
metadata:
  name: mqshare
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "extra" (list . "labels.service.mqshare" 4) }}
  annotations:
    {{- include "extra" (list . "annotations.service.mqshare" 4) }}
spec:
  ports:
    - name: mq
      port: {{ .Values.services.mqshare.ports.mq }}
    - name: console
      port: {{ .Values.services.mqshare.ports.console }}
  selector:
    app: mqshare
