apiVersion: apps/v1
kind: Deployment
metadata:
  name: isvgimconfig
  namespace: {{ .Values.namespace }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app: isvgimconfig
  template:
    metadata:
      labels:
        app: isvgimconfig
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: isvgimconfig
        image: {{ .Values.images.isvgim }}
        command: ["/bin/bash", "-c"]
        args:
        - >
          cp -rLv /tmp/isvgimdata/* /opt/ibm/wlp/usr/servers/defaultServer/config/data/ &&
          /work/util/fixup.sh /work/util/{{ .Chart.AppVersion }}-tweaks.patch &&
          /work/initIMContainer.sh config
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: DEBUG_INIT
          value: {{ .Values.services.isvgim.config.debugInitScripts | quote }}
        - name: TZ
          value: ":{{ .Values.timezone }}"
        envFrom:
        - secretRef:
            name: metricscreds
        volumeMounts:
        - mountPath: /tmp/isvgimcfg
          name: config
        - mountPath: /tmp/isvgimdata
          name: isvgimdatadir
        - mountPath: /work/util
          name: util
      restartPolicy: Always
      volumes:
      - name: config
        projected:
          defaultMode: 0640
          sources:
          - configMap:
              name: isvgimconfig
          - secret:
              name: isvgimcerts
      - name: keystore
        secret:
          secretName: isvgimks
          optional: true
          items:
          - key: encryptionKey.properties
            path: encryptionKey.properties
         {{- range $path, $_ := .Files.Glob "data/keystore/**" }}
          - key: {{ base $path | quote }}
            path: {{ trimPrefix "data/" $path | quote }}
         {{- end }}
      - name: properties
        configMap:
          name: isvgimdata2
      - name: properties-rest
        configMap:
          name: isvgimdata2-rest
      - name: init
        configMap:
          name: isvgim-init
          defaultMode: 0755
      - name: util
        configMap:
          name: isvgim-util
          defaultMode: 0755
      - name: isvgimdatadir
        emptyDir: {}
      initContainers:
      - name: isvgim-init
        image: {{ .Values.images.isvgim }}
        command: ["/work/init/pre-init.sh"]
        imagePullPolicy: IfNotPresent
        env:
        - name: DEBUG_INIT
          value: {{ .Values.services.isvgim.config.debugInitScripts | quote }}
        - name: TZ
          value: ":{{ .Values.timezone }}"
        envFrom:
        - secretRef:
            name: extcreds
        volumeMounts:
        - mountPath: /tmp/isvgimks
          name: keystore
        - mountPath: /tmp/isvgimdata
          name: properties
        - mountPath: /tmp/isvgimdata/rest
          name: properties-rest
        - mountPath: /work/init
          name: init
        - mountPath: /tmp/export
          name: isvgimdatadir
