general:
  install:
    createTablespace: true
    deployIsvdi: true
    deployDb: false
    deployLdap: false
    externalSecret:
      mqcreds: false
      extcreds: false
      oidccreds: false
  license:
    activationKey:
    accepted: true
    ldapKey:
    isvidKey:
    riskKey:
db:
  user: postgres
  password:
  dbtype:
  ip:
  port:
  name: ivig
  admin: postgres
  adminPwd:
  security.protocol: ssl
  tablespace.location.data: /var/lib/postgresql/data/isvgimdata
  tablespace.location.indexes: /var/lib/postgresql/data/isvgimindexes
ldap:
  security.principal: cn=root
  security.credentials:
  defaulttenant.id: demo
  organization.name: Demo
  ldapserver.ip:
  ldapserver.port:
  ldapserver.root: dc=ivig
  security.protocol: ssl
mail:
  authentication.type: basic
  baseurl: https://foo.com/
  from: ivig@foo.com
  host: mailservice.mailpit.svc.cluster.local
  smtp.port: 1025
  smtp.starttls.enable: false
  smtp.auth: true
  smtp.auth.user: ivig
  smtp.auth.password:
office365:
  monitoring.enabled: false
  user.id:
  tenant.id:
  client.id:
  client.secret:
  scan.interval.minutes:
  graph.token.endpoint:
  graph.messages.endpoint:
  graph.user.agent:
server:
  options:
  - name: libertyMetrics
    enabled: false
    data:
    - name: userName
      value: null
    - name: password
      value: null
  flags:
    disableTLSv12: false
    enableFIPS: false
  hostname: null
  truststore:
  - '@isvgimRootCA.crt'
  keystore: null
