apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    version-control/revision: {{ default "unknown" .Values.revision | quote }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace }}
    pod-security-kubernetes.io/enforce: baseline
    pod-security-kubernetes.io/enforce-version: v1.26
    pod-security-kubernetes.io/warn: baseline
    pod-security-kubernetes.io/warn-version: latest
