apiVersion: apps/v1
kind: Deployment
metadata:
  name: isvgimconfig
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isvgimconfig
  template:
    metadata:
      labels:
        app: isvgimconfig
    spec:
      imagePullSecrets:
      {{ if hasPrefix "icr.io" .Values.images.isvgim }}- name: ibmcloud{{else}}- name: regcred{{end}}
      containers:
      - name: isvgimconfig
        image: {{ .Values.images.isvgim }}
        command: [ "/bin/bash", "-c", "/work/initIMContainer.sh config" ]
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: DEBUG_INIT
          value: {{ .Values.services.isvgim.config.debugInitScripts | quote }}
        - name: TZ
          value: ":{{ .Values.timezone }}"
        volumeMounts:
        - mountPath: /tmp/isvgimcfg
          name: config
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: isvgimconfig

