apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ivig-idm
spec:
  # The destination defines the namespace and k8s cluster where to deploy to.
  destination:
    # Set the target namespace to the same value as defined in values.yaml. This
    # feels redundant, but Argo CD performs consistency validation and can be
    # configured to enforce allowed destinations via project restrictions.
    namespace: ivig-idm
    # Deploy to the local cluster (where Argo CD itself is running)
    server: https://kubernetes.default.svc
  # The source specifies the location and configuration of the Helm chart.
  source:
    # Location of the repository, matched against configured repo connections.
    # It is recommended to use HTTPS and API key based authentication.
    repoURL: https://git.example.com/foobar/myproject.git
    # The path to the Helm chart within the repository
    path: smarterkit
    # Git tag, branch or commit hash which identifies the revision to deploy.
    targetRevision: develop
    # This section controls how the Helm chart is rendered.
    helm:
      # Values (configuration data) can be specified via a default/override
      # pattern where multiple sources of configuration are merged top-down.
      #
      # 1. Values are read from files listed under source.helm.valueFiles. All
      #    files are merged top-down. Aborts if missing files are referenced.
      #
      # 2. The equivalent of a values file can be specified directly in the this
      #    app manifest using the source.helm.valuesObject key, the content of
      #    which is merged with values files, overriding conflicting values.
      #
      # 3. Individual parameters can be specified under source.helm.parameters
      #    in a path-based notation. These parameters are merged with the
      #    highest precedence, and will override any value defined above.
      valueFiles:
        # Typically, the solution is deployed to multiple isolated environments
        # which represent core stages such as DEV, TEST and PROD.
        # It is a good practice to split common configuration from stage
        # specific configuration.
        - values.yaml
        - values-config.yaml
        # In this example, the configuration files above this line are project
        # specific (common to all stages within the project) and the config file
        # below merely captures the values which are to be overridden on a
        # per-environment basis. This approach highly reduces redundancy.
        - values-override-DEV.yaml
      valuesObject:
        # For a demo or developer setup, insert the contents of secrets.yaml and
        # regcred.yaml indented by 8 spaces!
        # Alternatively, leave this section blank and source secrets from vault.
      parameters:
        # Annotating the k8s namespace with the git commit hash (or any other
        # revision identifier of your choice) allows to track what was deployed.
        - name: revision
          value: $ARGO_APP_REVISION_SHORT
        # Instead of storing license keys in git (e.g. in values-config.yaml)
        # let ArgoCD dynamically inject these values during template rendering.
        # CHANGE DUMMY VALUES in this sample file to your actual license keys!
        - name: general.license.activationKey
          value: XXAZ6-Z7O6E-H6DUA-Y1PBZ-5RS5X
        - name: general.license.ldapKey
          value: R2VuDGJSa0vqJH01+JKryHts2dRZy/8aCH0k2wq1Rxp3q/A36a5Uei4D...JWs=
        - name: general.license.isvdiKey
          value: UmVCYBaU+QRpmAtuTNp2VaUACVH29SCmgHeR9YGanL9tyPRmzmMmHRbF...ATw=
  # Projects enable logical grouping of applications and enable access control.
  # Define the project to assign to, if omitted, the default project is used.
  # If not using the default project, access control MUST be configured upfront.
  project: integrator
