{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
{{- if .Values.general.install.deployDb }}
{{-   if not (.Values.general.install.externalSecret).pgcerts }}
apiVersion: v1
kind: Secret
metadata:
  name: pgcerts
  namespace: {{ .Values.namespace }}
stringData:
{{ include "certs" (list . "pgsql.{key,crt}") }}
{{-   end }}
{{- end }}
