{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
{{- if .Values.general.install.deployDb }}
{{-   if not (.Values.general.install.externalSecret).pgcreds }}
apiVersion: v1
stringData:
  pguser: {{ .Values.db.user | default "postgres" | quote }}
  admuser: {{ .Values.db.admin | default "postgres" | quote }}
data:
  pgpass: {{ required "DB_PASSWORD missing!" .Values.DB_PASSWORD | b64enc }}
  admpass: {{ required "DBADMIN_PASSWORD missing!" .Values.DBADMIN_PASSWORD | b64enc }}
kind: Secret
metadata:
  name: pgcreds
  namespace: {{ .Values.namespace }}
{{-   end }}
{{- end }}
