{{- if .Values.general.install.deployDb }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
    {{- include "extra" (list . "labels.service.postgres" 4) }}
  annotations:
    {{- include "extra" (list . "annotations.service.postgres" 4) }}
spec:
  selector:
    app: postgres
  ports:
    - name: postgres-pg
      port: {{ .Values.services.postgres.ports.pg }}
      protocol: TCP
{{- end }}
