{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
{{- if .Values.general.install.deployIsvart }}
{{-   if not (.Values.general.install.externalSecret).isvartcerts }}
apiVersion: v1
kind: Secret
metadata:
  name: isvartcerts
  namespace: {{ .Values.namespace }}
stringData:
{{ include "certs" (list . "isvart.{key,crt}") }}
{{-   end }}
{{- end }}
