apiVersion: v1
kind: ConfigMap
metadata:
  name: tlsmqcfg
  namespace: {{ .Values.namespace }}
data:
{{ ( include "certs" (list . "{mq.key,mq.crt,isvgimRootCA.crt}") | .Files.Glob ).AsConfig | indent 2 }}
