apiVersion: v1
data:
  encryptionKey.properties: {{ .Files.Get "data/encryptionKey.properties" | b64enc }}
{{- $keypath := "" }}
{{- range $path, $_ := .Files.Glob "data/keystore/**" }}
{{- if (hasSuffix ".key" $path) }}
{{-   $keypath = trimPrefix "data/" $path | quote }}
{{- end }}
  {{ base $path }}: {{ $.Files.Get $path | b64enc }}
{{- end }}
kind: Secret
metadata:
  name: isvgimks
  namespace: {{ .Values.namespace }}
  annotations:
    isvgim/keypath: {{ $keypath | default "none" }}
