apiVersion: v1
kind: ConfigMap
metadata:
  name: isvgimconfig
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    version: '24.12'
    general:
      install:
        createTablespace: {{ .Values.general.install.createTablespace }}
      license:
        activationKey: {{ .Values.general.license.activationKey | default "null" }}
        accepted: true
        riskKey: {{ .Values.general.license.riskKey | default "null" }}
    server: {{- .Values.server | toYaml | nindent 6 }}
    {{- if .Values.oidc}}
    oidc: {{- .Values.oidc | toYaml | nindent 6 }}
    {{- end }}
{{- $files := .Files.Glob "{pre-init.sh,config/certs/*}" }}
{{- if gt (len $files) 0 }}
{{ $files.AsConfig | indent 2 }}
{{- end -}}
