{{- if not (.Values.general.install.externalSecret).isvgimcerts }}
apiVersion: v1
kind: Secret
metadata:
  name: isvgimcerts
  namespace: {{ .Values.namespace }}
stringData:
{{ (include "certs" (list . "*") | .Files.Glob).AsConfig | indent 2 }}
{{- end }}
