apiVersion: v1
data:
  mqadmin: {{ required "MQADMIN_PASSWORD missing!" .Values.MQADMIN_PASSWORD | b64enc }}
  mqlocal: {{ required "MQLOCAL_PASSWORD missing!" .Values.MQLOCAL_PASSWORD | b64enc }}
  mqshare: {{ required "MQSHARE_PASSWORD missing!" .Values.MQSHARE_PASSWORD | b64enc }}
kind: Secret
metadata:
  name: mqcreds
  namespace: {{ .Values.namespace }}
