apiVersion: v1
stringData:
  adminConsoleuser: {{ .Values.OIDC_ADMINCONSOLE_CLIENTID | default "adminuser" | quote }}
  iscuser: {{ .Values.OIDC_ISC_CLIENTID | default "iscuser" | quote }}
  restuser: {{ .Values.OIDC_REST_CLIENTID | default "restuser" | quote }}
data:
  adminConsolesecret: {{ .Values.OIDC_ADMINCONSOLE_SECRET | default "none"  | b64enc }}
  iscsecret: {{ .Values.OIDC_ISC_SECRET | default "none" | b64enc }}
  restsecret: {{ .Values.OIDC_REST_SECRET | default "none" | b64enc }}
kind: Secret
metadata:
  name: oidccreds
  namespace: {{ .Values.namespace }}
