apiVersion: v1
data:
  adminConsolesecret: ""
  adminConsoleuser: ""
  iscsecret: {{ required "ISC_SECRET missing!" .Values.ISC_SECRET | b64enc }}
  iscuser: {{ "extranetBw-isvg" | b64enc }}
  restsecret: {{ required "REST_SECRET missing!" .Values.REST_SECRET | b64enc }}
  restuser: {{ "extranetBw-isvg" | b64enc }}
kind: Secret
metadata:
  name: oidccreds
  namespace: {{ .Values.namespace }}
