version: '24.12'
general:
  install:
    createTablespace: {{ .Values.general.install.createTablespace }}
  license:
    activationKey: {{ .Values.general.license.activationKey }}
    accepted: true
    riskKey: null
server:
  options:
  - name: libertyMetrics
    enabled: false
    data:
    - name: userName
      value: null
    - name: password
      value: null
  flags:
    disableTLSv12: false
    enableFIPS: false
  hostname: null
  truststore:
  - '@isvgimRootCA.crt'
  keystore: null
