#********************************************************************
#* IBM Confidential - OCO Source Materials
#*
#* The source code for this program is not published or otherwise
#* divested of its trade secrets, irrespective of what has been
#* deposited with the U.S. Copyright Office.
#*
#* Licensed Materials - Property of IBM
#* Product ID = 5725-T18
#*
#* Copyright IBM Corp. 2025.
#*
#* US Government Users Restricted Rights - Use, duplication, or
#* disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#********************************************************************





###########################################################
# Database information
###########################################################
# Database type; The possible values are DB2, ORACLE, and POSTGRESQL
database.db.type={{ eq .Values.db.dbtype "db2" | ternary "DB2" "POSTGRESQL" }}

# ITIM Database owner
database.db.owner={{ .Values.db.user }}

# ITIM Database User
database.db.user={{ .Values.db.user }}

# ITIM database Password
database.db.password=

# The security protocol to use (e.g. "ssl")
database.db.security.protocol={{ index .Values.db "security.protocol" }}

############################################################
# Connection pool 
############################################################
# Connection pool properties
database.jdbc.connectionPool.initialCapacity=5
database.jdbc.connectionPool.maxCapacity=50

############################################################
# JDBC driver URL and driver name
#
############################################################
{{- if eq .Values.db.dbtype "db2" }}
# JDBC driver URL 
database.jdbc.driverUrl=jdbc:db2://{{ .Values.db.ip }}:{{ .Values.db.port  }}/{{ .Values.db.name }}{{ if eq (index .Values.db "security.protocol") "ssl" }}:sslConnection=true;{{ end }}

# JDBC driver name
database.jdbc.driver=com.ibm.db2.jdd.DB2Driver
{{- else }}
# JDBC driver URL 
database.jdbc.driverUrl=jdbc:postgresql://{{ .Values.db.ip | default "postgres" }}:{{ .Values.db.port  | default 5432 }}/{{ .Values.db.name | default "ivig" }}?autosave=always&currentSchema={{ .Values.db.user }}

# JDBC driver name
database.jdbc.driver=org.postgresql.Driver

database.tablespace.location.data={{ index .Values.db "tablespace.location.data" | default "/var/lib/postgresql/data/isvgimdata" }}
database.tablespace.location.indexes={{ index .Values.db "tablespace.location.data" | default "/var/lib/postgresql/data/isvgimindexes" }}
{{- end }} 

database.db.tablespaceFlag={{ .Values.general.install.createTablespace | default "false" }}
database.db.admin={{ .Values.db.admin }}
database.db.adminPwd=
