{{- if .Values.general.install.deployLdap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: isvgimldap
  namespace: {{ .Values.namespace }}
data:
{{ tpl (.Files.Glob "config/ldap/*.yaml").AsConfig . | indent 2 }}
{{- $files := include "certs" (list . "{isvd.pem,*.crt}") | .Files.Glob }}
{{- if gt (len $files) 0 }}
{{ $files.AsConfig | indent 2 }}
{{- end -}}
{{- end }}
