{{- if .Values.general.install.deployLdap }}
apiVersion: v1
stringData:
  admindn: {{ index .Values.ldap "security.principal" | default "cn=root" | quote }}
data:
  adminpwd: {{ required "LDAP_PASSWORD missing!" .Values.LDAP_PASSWORD | b64enc }}
kind: Secret
metadata:
  name: isvdcred
  namespace: {{ .Values.namespace }}
{{- end }}
