{{- if (.Values.vault).server }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: idm-vault-viewer
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: idm-vault-viewer-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: idm-vault-viewer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: idm-vault-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: idm-vault-viewer
    namespace: {{ .Values.namespace }}
{{- end }}
