{{- if .Values.vault }}
{{- range $key, $val := .Values.general.install.externalSecret }}
{{- if $val }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: {{ $.Values.vault.refreshInterval | quote | default "null" }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.vault.secretStore | default "idm-vault-secret-store" }}
  target:
    name: {{ $key }}
{{- if eq $key "regcred" }}
    template:
      type: kubernetes.io/dockerconfigjson
{{- end }}
  dataFrom:
    - extract:
       key: {{ hasSuffix "certs" $key | ternary "certs" "secrets" }}/{{ $key }}
---
{{- end }}
{{- end }}
{{- end }}
