{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
{{- if .Values.general.install.deployIsvdi }}
{{-   if not (.Values.general.install.externalSecret).isvdicerts }}
apiVersion: v1
kind: Secret
metadata:
  name: isvdicerts
  namespace: {{ .Values.namespace }}
stringData:
{{ include "certs" (list . "{isvdi.pem,*.crt}") }}
{{-   end }}
{{- end }}
