{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
{{- if .Values.general.install.deployIsvdi }}
apiVersion: v1
kind: Service
metadata:
  name: isvdi
  namespace: {{ .Values.namespace }}
  labels:
    app: isvdi
    {{- include "extra" (list . "labels.service.isvdi" 4) }}
  annotations:
    {{- include "extra" (list . "annotations.service.isvdi" 4) }}
spec:
  selector:
    app: isvdi
  ports:
    - name: rmi
      port: {{ .Values.services.isvdi.ports.api }}
      protocol: TCP
{{- end }}
