{{- if .Values.general.install.deployLdap }}
{{-   if not (.Values.general.install.externalSecret).isvdcerts }}
apiVersion: v1
kind: Secret
metadata:
  name: isvdcerts
  namespace: {{ .Values.namespace }}
stringData:
{{ include "certs" (list . "{isvd.pem,*.crt}") }}
{{-   end }}
{{- end }}
