{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
{{- if .Values.general.install.deployLdap }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replica-1-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.volumes.isvd }}
{{- end }}
