{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
{{- if .Values.general.install.deployLdap }}
apiVersion: v1
kind: Service
metadata:
  name: isvd-replica-1
  namespace: {{ .Values.namespace }}
  labels:
    app: isvd-server
    {{- include "extra" (list . "labels.service.isvd-replica-1" 4) }}
  annotations:
    {{- include "extra" (list . "annotations.service.isvd-replica-1" 4) }}
spec:
  selector:
    app: isvd-replica-1
  ports:
    - name: isvd-replica-1-ldaps
      port: {{ .Values.services.isvd.ports.ldaps }}
      protocol: TCP
{{- end }}
