#********************************************************************
#* Copyright IBM Corp. 2026
#* SPDX-License-Identifier: MIT
#********************************************************************

{{ with .Values.db }}
{{ $type := get (dict "db2" "DB2" "oracle" "ORACLE") (toString .dbtype) | default "POSTGRESQL" }}
{{ $ssl := eq (index . "security.protocol") "ssl" }}
{{ $jdbcDriver := get (dict "DB2" "com.ibm.db2.jdd.DB2Driver" "ORACLE" "oracle.jdbc.driver.OracleDriver" "POSTGRESQL" "org.postgresql.Driver") $type }}
###########################################################
# Database information
###########################################################
# Database type; The possible values are DB2, ORACLE, and POSTGRESQL
database.db.type={{ $type }}

# ITIM Database owner
database.db.owner={{ .user }}

# ITIM Database User
database.db.user={{ .user }}

# ITIM database Password
database.db.password=

# The security protocol to use (e.g. "ssl")
database.db.security.protocol={{ index . "security.protocol" }}

############################################################
# Connection pool
############################################################
# Connection pool properties
database.jdbc.connectionPool.initialCapacity=5
database.jdbc.connectionPool.maxCapacity=50

############################################################
# JDBC driver URL and driver name
#
############################################################
# JDBC driver URL
{{- if .forcedJdbcUrl }}
# explicitly configured JDBC URL via db.forcedJdbcUrl
database.jdbc.driverUrl={{ .forcedJdbcUrl }}

{{- else if eq $type "DB2" }}
database.jdbc.driverUrl=jdbc:db2://{{ .ip }}:{{ .port }}/{{ .name }}{{ if $ssl }}:sslConnection=true;{{ end }}

{{- else if eq $type "ORACLE" }}
database.jdbc.driverUrl=jdbc:oracle:thin:@
{{- if $ssl }}
{{- printf "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=%s)(PORT=%v))(CONNECT_DATA=(%s=%s)))" .ip .port (ternary "SERVICE_NAME" "SID" .isOracleServiceName) .name }}
{{- else }}
{{- printf (ternary "//%s:%v/%s" "%s:%v:%s" .isOracleServiceName) .ip .port .name }}
{{- end }}

{{- else }}{{/* POSTGRESQL explicitly or implicitly */}}
database.jdbc.driverUrl=jdbc:postgresql://{{ .ip | default "postgres" }}:{{ .port | default 5432 }}/{{ .name | default "ivig" }}?autosave=always&currentSchema={{ .user }}
{{- end }}

# JDBC driver name
database.jdbc.driver={{ $jdbcDriver }}

{{- if eq $type "POSTGRESQL" }}
database.tablespace.location.data={{ index . "tablespace.location.data" | default "/var/lib/postgresql/data/isvgimdata" }}
database.tablespace.location.indexes={{ index . "tablespace.location.indexes" | default "/var/lib/postgresql/data/isvgimindexes" }}
{{- end }}

database.db.tablespaceFlag={{ $.Values.general.install.createTablespace | default "false" }}
database.db.admin={{ .admin }}
database.db.adminPwd=
{{- end }}
