#********************************************************************
#* Copyright IBM Corp. 2026
#* SPDX-License-Identifier: MIT
#********************************************************************




#------------------------------------------------------
# Properties used for LDAP connections.
#------------------------------------------------------

#
# Context.INITIAL_CONTEXT_FACTORY
#
# Defines the initial context factory to use to create
# the JNDI service provider
#
#java.naming.factory.initial=com.ibm.itim.test.prestate.server.JackedInitialContextFactory
java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory

#
# Context.PROVIDER_URL
#
# URL for the LDAP server.
java.naming.provider.url=ldap://{{ index .Values.ldap "ldapserver.ip" | default "isvd-replica-1" }}:{{ index .Values.ldap "ldapserver.port"  | default 9636 }}

#
# Context.SECURITY_PRINCIPAL
#
# DN of the principal.
#
java.naming.security.principal={{ index .Values.ldap "security.principal" }}

#
# Context.SECURITY_CREDENTIALS
#
# Hashed password, clear-text password, key, certificate, etc.
#
java.naming.security.credentials=

#
# Context.SECURITY_PROTOCOL
#
# The security protocol to use (e.g. "ssl").
#
java.naming.security.protocol={{ index .Values.ldap "security.protocol" }}

#
# Context.SECURITY_AUTHENTICATION
#
# Type of authentication to use. Is one of "none", "simple", or "strong".
#
java.naming.security.authentication=simple

#
# Context.REFERRAL
#
# The behaviour when referrals are encountered. Is one of "follow",
# "ignore", or "throw"
#
java.naming.referral=follow

#
# Context.BATCHSIZE
#
# The batch size to use for returning data. Must be an integer.
#
java.naming.batchsize=100

#
# Dereferencing Aliases
#
# When you look up an object by using the alias, the alias is dereferenced
# so that what is returned is the object pointed to by the alias's DN.
# Is one of "never", "always", "finding" (only during name resolution), or
# "searching" (only after name resolution)
#
java.naming.ldap.derefAliases=never

#
# attributes.binary
#
# The list of attributes define for binary data type. Multiple values separated by a space.
#
java.naming.ldap.attributes.binary=erPassword erHistoricalPassword erSynchPassword erServicePassword erPersonPassword

#-----------------------------#
# POOLING SPECIFIC PROPERTIES #
#-----------------------------#

#
# Activates the ldap connection pool
#
com.sun.jndi.ldap.connect.pool=true

#
# Timeout for pooled connection to become available
#
# The string representation of an integer that represents the number of milliseconds that a
# client will wait for a pooled connection to become available. If the property is not specified
# the client will wait indefinitely.
#com.sun.jndi.ldap.connect.timeout=
javax.net.ssl.trustStorePassword=
javax.net.ssl.trustStore=/opt/ibm/wlp/usr/servers/defaultServer/resources/security/isvgimTruststore.jks
